
site_name: Chinese Learning Notes
site_url: https://martinlicht.github.io/chinese/
theme:
  name: material
  palette:
    - scheme: default
      primary: amber
      accent: red
    - scheme: slate
      primary: blue grey
      accent: lime
markdown_extensions:
  - admonition
  - tables
nav:
  - Home: index.md
  - Basics:
      - Introducing yourself: notes/introducing.md
      - Greetings: notes/greetings.md
  - Numbers:
      - 0 to 10: notes/numbers0to10.md
      - 1 to 99: notes/numbers1to99.md
      - Three-digit numbers: notes/three_digit_numbers.md
      - Four-digit numbers: notes/four_digit_numbers.md
      - Chinese phone numbers: notes/chinese_phone_numbers.md
      - Er vs Liang: notes/er_vs_liang.md
  - Grammar:
      - 差点儿 / 差一点儿: notes/chadianr.md
      - Both with 两个都: notes/liang_ge_dou.md
      - Word order: notes/word_order.md



hooks:
  - hooks/chinese.py

extra_javascript:
  - js/chinese-audio.js

extra_css:
  - css/chinese-audio.css
